# Риск остеопороза у женщин

Для 500 участниц исследования Global Longitudinal Study of Osteoporosis in Women (Center for Outcomes Research, the University of Massachusetts/Worcester) измерены следующие показатели:

* возраст, лет (не меньше 55);
* вес, кг;
* рост, см;
* ИМТ, кг/см2;
* бинарные признаки: курение, индикатор наступления менопаузы до 45 лет, индикатор необходимости помощи при подъёме из сидячего положения, перелом шейки бедра в прошлом (был/не было), перелом шейки бедра у матери (был/не было);
* самостоятельная субъективная оценка вероятности перелома (меньше/такая же/больше, чем у сверстниц).


Известно, у кого из участниц в первый год исследования произошёл перелом шейки бедра. Необходимо построить модель вероятности перелома с учётом имеющихся признаков.

In [1]:
import pandas as pd
df = pd.read_csv('GLOW500.txt', sep='\t')
df.head()

,PRIORFRAC,AGE,WEIGHT,HEIGHT,BMI,PREMENO,MOMFRAC,ARMASSIST,SMOKE,RATERISK,FRACTURE
0,no,62,70.3,158,28.16055,no,no,no,no,same,no
1,no,65,87.1,160,34.02344,no,no,no,no,same,no
2,yes,88,50.8,157,20.60936,no,yes,yes,no,less,no
3,no,82,62.1,160,24.25781,no,no,no,no,less,no
4,no,61,68.0,152,29.43213,no,no,no,no,same,no